-- local oil = require('oil')
local keymap = vim.keymap
-- local oil = require('oil')
--
-- oil.setup {
--   default_file_explorer = true,
--   columns = {
--     'icon',
--     --'permissions',
--     --'size',
--     --'mtime',
--   },
--   -- [[ Default keymaps]]
--   -- keymaps = {
--   --   ['g?'] = 'actions.show_help',
--   --   ['<CR>'] = 'actions.select',
--   --   ['<C-s>'] = 'actions.select_vsplit',
--   --   ['<C-h>'] = 'actions.select_split',
--   --   ['<C-t>'] = 'actions.select_tab',
--   --   ['<C-p>'] = 'actions.preview',
--   --   ['<C-c>'] = 'actions.close',
--   --   ['<C-l>'] = 'actions.refresh',
--   --   ['-'] = 'actions.parent',
--   --   ['_'] = 'actions.open_cwd',
--   --   ['`'] = 'actions.cd',
--   --   ['~'] = 'actions.tcd',
--   --   ['gs'] = 'actions.change_sort',
--   --   ['gx'] = 'actions.open_external',
--   --   ['g.'] = 'actions.toggle_hidden',
--   -- },
-- }

keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
